version: '3.8'

services:
  mongodb:
    image: mongo:latest

    container_name: assite-ai-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  redis:
    image: redis:7-alpine
    container_name: assite-ai-redis
    restart: always
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
volumes:
  mongodata:
  redisdata:
